[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/CaloriesTrackerBackend/Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/calories/categories"
healthcheckTimeout = 300
